# Site settings
lang: en
permalink: pretty

# Profile
name: Ayush Sawarni
title: OR PhD Student
institution: Stanford University
email: ayushsaw@stanford.edu
location: Stanford, CA
short_bio: >-
  I am a second-year Operations Research PhD student at Stanford University where I work on causal inference, bandit algorithms, and learning from human feedback.

# Meta
keywords:
  - causal inference
  - bandits
  - operations research
  - machine learning
  - fairness
  - llm evaluation
description: Personal academic website for Ayush Sawarni.
url: ""
baseurl: ""

# Social links
social:
  google_scholar: https://scholar.google.com/citations?user=U8TSPdAAAAAJ&hl=en&oi=ao
  cv: assets/files/ayush_CV.pdf
  github: https://github.com/sawarniayush
  linkedin: https://www.linkedin.com/in/ayush-sawarni/
  twitter: https://twitter.com/ayushsawarni

# Assets
avatar: /assets/img/2EE4D34E-9124-4015-8C94-69D582072620_1_201_a.jpeg
favicon: /assets/img/club.png

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - vendor

sass:
  style: compressed

# Collections
collections:
  posts:
    output: true

