name: Update publications include

on:
  push:
    branches: [ main ]
    paths:
      - publications.bib
      - scripts/generate_publications.py
  workflow_dispatch:

jobs:
  generate-include:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Regenerate publications include
        run: python3 scripts/generate_publications.py

      - name: Commit and push changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Update publications include"
          git push
